import { getOverview } from "./lib/data";
import { Badge, Empty, Shell, Stat } from "./ui";

export const dynamic = "force-dynamic";

function formatDate(value: Date | null) { return value ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(value) : "Never"; }

export default async function Home() {
  const data = await getOverview();
  const reminder = data.todayPosts < data.dailyMinimum ? `${data.todayPosts} of ${data.dailyMinimum} minimum posts completed today.` : data.todayPosts < data.dailyPreferred ? `Daily minimum reached. ${data.todayPosts} of ${data.dailyPreferred} preferred posts completed.` : data.todayPosts === data.dailyPreferred ? `Preferred daily goal reached: ${data.todayPosts} posts.` : `${data.todayPosts} posts today, above the preferred goal of ${data.dailyPreferred}.`;
  return <Shell title="Overview" eyebrow="Cenblue / control room"><section className="hero"><div><p className="kicker">Local-first repost pipeline</p><h2>Keep the signal moving.</h2><p className="muted">{reminder}</p></div><div className="hero-orbit" aria-hidden="true"><span /><span /><span /></div></section><div className="stat-grid"><Stat label="Published today" value={data.todayPosts} detail={`goal ${data.dailyMinimum}-${data.dailyPreferred}`} accent="mint" /><Stat label="Enabled sources" value={data.enabledSources} detail="configured accounts" accent="blue" /><Stat label="Pending downloads" value={data.pendingDownloads} detail={`${data.failedDownloads} failed`} accent="orange" /><Stat label="Scheduled publishes" value={data.scheduledPublishes} detail={`${data.failedPublishes} need attention`} accent="mint" /></div><div className="two-col"><section className="panel"><div className="panel-head"><div><p className="eyebrow">Recent output</p><h3>Published posts</h3></div><a className="text-link" href="/published">View all →</a></div>{data.recentPublished.length === 0 ? <Empty>No published posts yet.</Empty> : <div className="feed">{data.recentPublished.map((record) => <div className="feed-row" key={record.id}><div className="feed-icon" aria-hidden="true">↗</div><div><strong>{record.publishJob.sourcePost.text || "Untitled post"}</strong><small>{formatDate(record.publishedAt)}</small></div><Badge value="PUBLISHED" /></div>)}</div>}</section><section className="panel health"><div className="panel-head"><div><p className="eyebrow">Activity summary</p><h3>Local runtime</h3></div><Badge value={data.browserBusy ? "RUNNING" : "AVAILABLE"} /></div><div className="health-list"><div><span className="health-dot blue" />Collector<strong>{data.collectionRun ? `${data.collectionRun.status.replaceAll("_", " ")} · ${data.collectionRun.completedSources}/${data.collectionRun.totalSources}` : `Last success ${formatDate(data.lastCollectedAt)}`}</strong></div><div><span className="health-dot blue" />Browser profile<strong>{data.browserBusy ? "In use by an X operation" : "Available"}</strong></div><div><span className="health-dot blue" />Runtime reports<strong>{data.runtime.length ? data.runtime.map((item) => `${item.component}: ${item.status}`).join(" · ") : "No worker report yet"}</strong></div></div></section></div></Shell>;
}
