import { bulkDownloadAction, cancelJob, changeJobStatus, downloadNow, processPendingDownloads, publishNow, resolveManualAttention, retryJob, schedulePublish } from "../actions";
import { ActionForm, ConfirmSubmitButton, DownloadProgress, SubmitButton } from "../controls";
import { getQueue, getSettings } from "../lib/data";
import { Badge, Empty, Shell } from "../ui";

export const dynamic = "force-dynamic";

export default async function QueuePage({ searchParams }: { searchParams: Promise<{ status?: string; source?: string; page?: string; actionError?: string }> }) {
  const params = await searchParams;
  const [{ downloads, publishes, sources, statuses, page }, settings] = await Promise.all([getQueue({ status: params.status, source: params.source, page: Number(params.page) || 1 }), getSettings()]);
  const actionableDownloads = downloads.filter((job) => ["PENDING", "FAILED", "RETRY_WAIT", "CANCELLED"].includes(job.status)).length;

  return <Shell title="Queue" eyebrow="Cenblue / durable work">
    <form className="queue-filters" method="get"><label>Status<select name="status" defaultValue={params.status ?? ""}><option value="">All statuses</option>{statuses.map((status) => <option key={status} value={status}>{status.replaceAll("_", " ").toLowerCase().replace(/^./, (letter) => letter.toUpperCase())}</option>)}</select></label><label>Source<select name="source" defaultValue={params.source ?? ""}><option value="">All sources</option>{sources.map((source) => <option key={source.username} value={source.username}>@{source.username}</option>)}</select></label><button className="small-button accent-button" type="submit">Apply filters</button>{(params.status || params.source) && <a className="small-button" href="/queue">Clear</a>}</form>
    {params.actionError && <div className="toast error" role="alert">{params.actionError}</div>}
    {settings.publishMode === "AUTOMATIC" && !settings.publisherSessionVerifiedAt && <div className="toast error" role="alert">Automatic publishing is paused because the publisher browser session has not been verified.</div>}
    <div className="panel">
      <div className="panel-head"><div><p className="eyebrow">Download jobs</p><h3>{downloads.length} operations · {actionableDownloads} actionable</h3></div><ActionForm action={processPendingDownloads} className="inline-form download-run-form"><label>Limit<input name="limit" type="number" min="1" max="1000" defaultValue={settings.downloadBatchLimit} required /></label><SubmitButton className="button primary" pending="Processing downloads…">Process pending now</SubmitButton></ActionForm></div>
      <DownloadProgress />
      {downloads.length === 0 ? <Empty>No download jobs in the queue.</Empty> : <div className="table-wrap queue-table-wrap"><table className="queue-table">
        <thead><tr><th>Select</th><th>Source post</th><th>Status</th><th>Attempts</th><th>Next attempt</th><th>Error</th><th>Actions</th></tr></thead>
        <tbody>{downloads.map((job) => <tr key={job.id}>
          <td data-label="Select">{["PENDING", "FAILED", "RETRY_WAIT", "CANCELLED"].includes(job.status) && <input form="bulk-downloads" type="checkbox" name="jobId" value={job.id} aria-label={`Select download ${job.sourcePost.platformPostId}`} />}</td><td data-label="Source post"><strong>@{job.sourcePost.sourceAccount.username}</strong><small><a className="text-link" href={job.sourcePost.sourceUrl} target="_blank" rel="noreferrer">X status {job.sourcePost.platformPostId} ↗</a></small></td><td data-label="Status"><Badge value={job.status} />{!["RUNNING", "COMPLETED"].includes(job.status) && <details className="status-editor"><summary>Change</summary><ActionForm action={changeJobStatus} className="inline-form"><input type="hidden" name="jobId" value={job.id} /><input type="hidden" name="jobType" value="download" /><select name="status" defaultValue={job.status === "CANCELLED" ? "CANCELLED" : "PENDING"}><option value="PENDING">Pending</option><option value="CANCELLED">Cancelled</option></select><SubmitButton>Set</SubmitButton></ActionForm></details>}</td><td data-label="Attempts">{job.attemptCount}</td><td data-label="Next attempt">{job.nextAttemptAt ? new Date(job.nextAttemptAt).toLocaleString() : ["PENDING", "RETRY_WAIT"].includes(job.status) ? "Now" : "—"}</td><td data-label="Error"><small className="table-error">{job.lastError ?? "—"}</small></td>
          <td data-label="Actions"><div className="actions">
            {["PENDING", "FAILED", "RETRY_WAIT", "CANCELLED"].includes(job.status) && <ActionForm action={downloadNow}><input type="hidden" name="jobId" value={job.id} /><SubmitButton className="small-button accent-button" pending="Downloading…">Download now</SubmitButton></ActionForm>}
            {["FAILED", "RETRY_WAIT", "CANCELLED"].includes(job.status) && <ActionForm action={retryJob}><input type="hidden" name="jobId" value={job.id} /><input type="hidden" name="jobType" value="download" /><SubmitButton>Queue retry</SubmitButton></ActionForm>}
            {["PENDING", "RETRY_WAIT", "FAILED"].includes(job.status) && <ActionForm action={cancelJob}><input type="hidden" name="jobId" value={job.id} /><input type="hidden" name="jobType" value="download" /><ConfirmSubmitButton message={`Cancel download for post ${job.sourcePost.platformPostId}?`}>Cancel</ConfirmSubmitButton></ActionForm>}
          </div></td>
        </tr>)}</tbody>
      </table></div>}<ActionForm action={bulkDownloadAction} id="bulk-downloads" className="actions"><button name="operation" value="retry" className="small-button">Bulk queue retry</button><button name="operation" value="download" className="small-button accent-button">Bulk download now</button></ActionForm>
    </div>

    <div className="panel">
      <div className="panel-head"><div><p className="eyebrow">Publish jobs</p><h3>{publishes.length} scheduled operations</h3></div><span className="count-chip">Auto-check every 30 seconds</span></div>
      {publishes.length === 0 ? <Empty>No publish jobs scheduled.</Empty> : <div className="table-wrap queue-table-wrap"><table className="queue-table">
        <thead><tr><th>Post</th><th>Status</th><th>Scheduled for</th><th>Attempts</th><th>Error</th><th>Actions</th></tr></thead>
        <tbody>{publishes.map((job) => <tr key={job.id}>
          <td data-label="Post"><strong>@{job.sourcePost.sourceAccount.username}</strong><small>{job.caption || "No caption"}</small><small>{(job.mediaAsset.fileSize / 1_000_000).toFixed(1)} MB · {job.mediaAsset.durationSeconds.toFixed(0)}s{job.mediaAsset.fileSize >= 100_000_000 || job.mediaAsset.durationSeconds >= 600 ? " · Large upload" : ""}</small><small><a className="text-link" href={job.sourcePost.sourceUrl} target="_blank" rel="noreferrer">X status {job.sourcePost.platformPostId} ↗</a></small></td><td data-label="Status"><Badge value={job.status} />{job.phase ? <small>{job.phase.replaceAll("_", " ")}</small> : null}{!["RUNNING", "PUBLISHING", "COMPLETED"].includes(job.status) && <details className="status-editor"><summary>Change</summary><ActionForm action={changeJobStatus} className="inline-form"><input type="hidden" name="jobId" value={job.id} /><input type="hidden" name="jobType" value="publish" /><select name="status" defaultValue={["APPROVED", "REJECTED", "READY_FOR_REVIEW"].includes(job.status) ? job.status : "READY_FOR_REVIEW"}><option value="READY_FOR_REVIEW">Ready for review</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option></select><SubmitButton>Set</SubmitButton></ActionForm></details>}</td><td data-label="Scheduled for">{job.scheduledFor ? new Date(job.scheduledFor).toLocaleString() : "Immediate"}</td><td data-label="Attempts">{job.attemptCount}</td><td data-label="Error"><small className="table-error">{job.lastError ?? "—"}</small></td>
          <td data-label="Actions"><div className="actions">{["APPROVED", "RETRY_WAIT"].includes(job.status) && (!job.scheduledFor || job.scheduledFor <= new Date()) && (!job.nextAttemptAt || job.nextAttemptAt <= new Date()) && <ActionForm action={publishNow}><input type="hidden" name="publishJobId" value={job.id} /><ConfirmSubmitButton className="small-button accent-button" pendingLabel="Publishing…" message={`Publish X post ${job.sourcePost.platformPostId} now with this caption?\n\n${job.caption || "(empty caption)"}`}>Publish now</ConfirmSubmitButton></ActionForm>}{["APPROVED", "RETRY_WAIT"].includes(job.status) && <ActionForm action={schedulePublish} className="schedule-form"><input type="hidden" name="publishJobId" value={job.id} /><input aria-label="New local schedule time" type="datetime-local" name="scheduledFor" step="60" required /><SubmitButton>Reschedule</SubmitButton></ActionForm>}{["FAILED", "RETRY_WAIT"].includes(job.status) && <ActionForm action={retryJob}><input type="hidden" name="jobId" value={job.id} /><input type="hidden" name="jobType" value="publish" /><SubmitButton>Retry</SubmitButton></ActionForm>}{job.status === "MANUAL_ATTENTION" && <ActionForm action={resolveManualAttention}><input type="hidden" name="publishJobId" value={job.id} /><ConfirmSubmitButton message={`Confirm X post ${job.sourcePost.platformPostId} was not published, then return it to Review?`}>Verified not published</ConfirmSubmitButton></ActionForm>}{["APPROVED", "RETRY_WAIT"].includes(job.status) && <ActionForm action={cancelJob}><input type="hidden" name="jobId" value={job.id} /><input type="hidden" name="jobType" value="publish" /><ConfirmSubmitButton message={`Return publish job for post ${job.sourcePost.platformPostId} to review?`}>Return to review</ConfirmSubmitButton></ActionForm>}</div></td>
        </tr>)}</tbody>
      </table></div>}
    </div>
    {(downloads.length === 50 || publishes.length === 50 || page > 1) && <nav className="queue-pagination" aria-label="Queue pagination">{page > 1 && <a className="small-button" href={`/queue?${new URLSearchParams({ ...(params.status ? { status: params.status } : {}), ...(params.source ? { source: params.source } : {}), page: String(page - 1) })}`}>Previous</a>}<span>Page {page}</span>{(downloads.length === 50 || publishes.length === 50) && <a className="small-button" href={`/queue?${new URLSearchParams({ ...(params.status ? { status: params.status } : {}), ...(params.source ? { source: params.source } : {}), page: String(page + 1) })}`}>Next</a>}</nav>}
  </Shell>;
}
