import { bulkReview, restoreDuplicate, scheduleBatchReview } from "../actions";
import { ActionForm, ConfirmSubmitButton, SubmitButton } from "../controls";
import { getReviewQueue, getSettings } from "../lib/data";
import { Empty, Shell } from "../ui";
import { ReviewList } from "./review-list";
import { ScheduleField } from "../schedule-field";

export const dynamic = "force-dynamic";

export default async function ReviewPage({ searchParams }: { searchParams: Promise<{ source?: string; sort?: string; compression?: string; before?: string; after?: string; batchScheduled?: string; batchDay?: string; batchEndDay?: string; batchInterval?: string; batchFirst?: string }> }) {
  const params = await searchParams;
  const [{ jobs, duplicates, sources, publishers }, settings] = await Promise.all([getReviewQueue(params.source, params.sort), getSettings()]);
  const today = new Intl.DateTimeFormat("en-CA", { timeZone: settings.timezone }).format(new Date());
  return <Shell title="Content review" eyebrow="Cenblue / approval required">
    {params.batchScheduled && <div className="toast bookmark-success" role="status">Batch scheduled: {params.batchScheduled} post{params.batchScheduled === "1" ? "" : "s"}{params.batchEndDay && params.batchEndDay !== params.batchDay ? ` · ${params.batchDay} – ${params.batchEndDay}` : ` on ${params.batchDay}`} · first ~{params.batchFirst ? new Date(params.batchFirst).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "auto"} · roughly every {params.batchInterval ? `${Math.round(Number(params.batchInterval) / 60)}h ${Number(params.batchInterval) % 60}m` : "—"}</div>}
    <form className="queue-filters" method="get"><label>Source<select name="source" defaultValue={params.source ?? ""}><option value="">All sources</option>{sources.map((source) => <option key={source.username} value={source.username}>@{source.username}</option>)}</select></label><label>Sort by<select name="sort" defaultValue={params.sort ?? "oldest"}><option value="oldest">Oldest waiting</option><option value="newest">Newest updated</option><option value="post-newest">Newest post</option><option value="post-oldest">Oldest post</option><option value="largest">Largest file</option><option value="smallest">Smallest file</option><option value="longest">Longest video</option><option value="shortest">Shortest video</option><option value="caption-longest">Longest caption</option><option value="caption-shortest">Shortest caption</option><option value="source-az">Source A-Z</option><option value="source-za">Source Z-A</option></select></label><button className="small-button accent-button" type="submit">Apply</button>{(params.source || (params.sort && params.sort !== "oldest")) && <a className="small-button" href="/review">Clear</a>}</form>
    <section className="panel review-guide"><p className="eyebrow">Publishing</p><strong>1. Preview and customize the caption. 2. Approve without a time for manual Queue publishing, or choose a schedule for automatic publishing while the dashboard is running.</strong></section>
    {params.compression === "saved" && <div className="toast bookmark-success" role="status">Video compressed from {(Number(params.before) / 1_000_000).toFixed(1)} MB to {(Number(params.after) / 1_000_000).toFixed(1)} MB.</div>}
    {params.compression === "not-smaller" && <div className="toast" role="status">The compressed candidate was not smaller, so the original video was kept.</div>}
    <section className="panel">
      <div className="panel-head"><div><p className="eyebrow">Manual queue</p><h3>{jobs.length} item{jobs.length === 1 ? "" : "s"} awaiting a decision</h3></div></div>
      {jobs.length > 0 && <details className="bulk-actions"><summary>Bulk actions for selected posts</summary><ActionForm action={bulkReview} id="bulk-review" className="bulk-review-actions"><fieldset className="publisher-targets"><legend>Publisher targets</legend>{publishers.map((publisher) => <label key={publisher.id}><input type="checkbox" name="publisherIdentityId" value={publisher.id} />{publisher.label} (@{publisher.expectedUsername})</label>)}</fieldset><ScheduleField timeZone={settings.timezone} optional /><ConfirmSubmitButton className="small-button accent-button" message="Approve the checked review posts for every selected Publisher?" name="decision" value="approve">Approve selected</ConfirmSubmitButton><ConfirmSubmitButton message="Reject only the checked review posts?" name="decision" value="reject">Reject selected</ConfirmSubmitButton><ConfirmSubmitButton message="Return only the checked posts to Downloads?" name="decision" value="downloads">Return selected to Downloads</ConfirmSubmitButton></ActionForm>
      <div className="batch-schedule"><p className="eyebrow">Batch schedule</p><h3>Shuffle + auto-assign times</h3><p className="form-note">The selected posts are shuffled and spaced across the active window ({settings.scheduleActiveWindows.map((w) => `${w.start}–${w.end}`).join(", ")}) with up to {settings.scheduleJitterMinutes} min jitter and a {settings.scheduleMinGapMinutes} min minimum gap. Nothing posts during the quiet hours. A window that crosses midnight (start after end) posts overnight and keeps the day quiet. When the batch is larger than one window, the remaining posts auto-spill into the following days with the same active hours.</p><ActionForm id="batch-schedule" action={scheduleBatchReview} className="bulk-review-actions"><fieldset className="publisher-targets"><legend>Publisher targets</legend>{publishers.map((publisher) => <label key={publisher.id}><input type="checkbox" name="publisherIdentityId" value={publisher.id} />{publisher.label} (@{publisher.expectedUsername})</label>)}</fieldset><label>Schedule day<input name="scheduleDay" type="date" defaultValue={today} /></label><label>Posts per day <span className="input-suffix">optional</span><input name="postsPerDay" type="number" min="1" max="50" placeholder="Fills the active window" /></label><ConfirmSubmitButton className="small-button accent-button" message="Shuffle, auto-assign times, and approve the checked review posts?">Batch schedule selected</ConfirmSubmitButton></ActionForm></div></details>}
      {jobs.length === 0 ? <Empty>No content is waiting for review.</Empty> : <ReviewList timeZone={settings.timezone} reviewers={{ previewEnabled: settings.reviewVideoPreviewEnabled === "true" }} publishers={publishers} jobs={jobs.map((job) => ({ id: job.id, status: job.status, caption: job.caption, scheduledFor: job.scheduledFor?.toISOString() ?? null, sourcePost: { platformPostId: job.sourcePost.platformPostId, sourceUrl: job.sourcePost.sourceUrl, text: job.sourcePost.text, discoveryKind: job.sourcePost.discoveryKind, reviewNotes: job.sourcePost.reviewNotes, internalTags: job.sourcePost.internalTags, username: job.sourcePost.sourceAccount.username, duplicateReason: job.sourcePost.duplicateReason }, mediaAsset: { fileSize: job.mediaAsset.fileSize, durationSeconds: job.mediaAsset.durationSeconds, width: job.mediaAsset.width, height: job.mediaAsset.height, compressed: job.mediaAsset.filePath.includes(".compressed-") } }))} />}
    </section>
    {duplicates.length > 0 && <section className="panel"><div className="panel-head"><div><p className="eyebrow">Skipped duplicates</p><h3>{duplicates.length} item{duplicates.length === 1 ? "" : "s"}</h3></div></div><div className="source-list">{duplicates.map((post) => <article className="source-row" key={post.id}><div className="source-main min-w-0"><strong className="[overflow-wrap:anywhere]">@{post.sourceAccount.username} · X status {post.platformPostId}</strong><small className="[overflow-wrap:anywhere]">{post.duplicateReason}</small>{post.mediaAsset && <video className="mt-3 block w-full max-w-[360px]" controls preload="metadata" src={`/media/${post.platformPostId}`} />}<ActionForm action={restoreDuplicate}><input type="hidden" name="sourcePostId" value={post.id} /><SubmitButton>Restore for review</SubmitButton></ActionForm></div></article>)}</div></section>}
  </Shell>;
}
