import { approveReview, bulkReview, rejectReview, resolveReviewCaption, restoreDuplicate, returnToDownloads } from "../actions";
import { ActionForm, ConfirmSubmitButton, SubmitButton } from "../controls";
import { getReviewQueue } from "../lib/data";
import { Badge, Empty, Shell } from "../ui";

export const dynamic = "force-dynamic";

export default async function ReviewPage({ searchParams }: { searchParams: Promise<{ source?: string; sort?: string }> }) {
  const params = await searchParams;
  const { jobs, duplicates, sources } = await getReviewQueue(params.source, params.sort);
  return <Shell title="Content review" eyebrow="Cenblue / approval required">
    <form className="queue-filters" method="get"><label>Source<select name="source" defaultValue={params.source ?? ""}><option value="">All sources</option>{sources.map((source) => <option key={source.username} value={source.username}>@{source.username}</option>)}</select></label><label>Sort by<select name="sort" defaultValue={params.sort ?? "oldest"}><option value="oldest">Oldest waiting</option><option value="newest">Newest first</option><option value="largest">Largest file</option><option value="smallest">Smallest file</option><option value="longest">Longest video</option><option value="shortest">Shortest video</option><option value="caption-longest">Longest caption</option><option value="caption-shortest">Shortest caption</option><option value="source-az">Source A-Z</option><option value="source-za">Source Z-A</option></select></label><button className="small-button accent-button" type="submit">Apply</button>{(params.source || (params.sort && params.sort !== "oldest")) && <a className="small-button" href="/review">Clear</a>}</form>
    <section className="panel review-guide"><p className="eyebrow">Publishing</p><strong>1. Preview and customize the caption. 2. Approve without a time for manual Queue publishing, or choose a schedule for automatic publishing while the dashboard is running.</strong></section>
    <section className="panel">
      <div className="panel-head"><div><p className="eyebrow">Manual queue</p><h3>{jobs.length} item{jobs.length === 1 ? "" : "s"} awaiting a decision</h3></div></div>
      {jobs.length > 0 && <details className="bulk-actions"><summary>Bulk actions for selected posts</summary><ActionForm action={bulkReview} id="bulk-review" className="bulk-review-actions"><label>Bulk schedule (local, required only when approving)<input name="scheduledFor" type="datetime-local" step="60" /></label><ConfirmSubmitButton className="small-button accent-button" message="Approve only the checked review posts?" name="decision" value="approve">Approve selected</ConfirmSubmitButton><ConfirmSubmitButton message="Reject only the checked review posts?" name="decision" value="reject">Reject selected</ConfirmSubmitButton><ConfirmSubmitButton message="Return only the checked posts to Downloads?" name="decision" value="downloads">Return selected to Downloads</ConfirmSubmitButton></ActionForm></details>}
      {jobs.length === 0 ? <Empty>No content is waiting for review.</Empty> : <div className="review-grid">{jobs.map((job) => <article className="review-card" key={job.id}>
        <div className="review-media">{job.mediaAsset ? <div><div className="review-media-meta"><strong>{(job.mediaAsset.fileSize / 1_000_000).toFixed(1)} MB</strong><span>{job.mediaAsset.durationSeconds.toFixed(1)}s</span><small>{job.mediaAsset.width}x{job.mediaAsset.height}</small></div><details className="review-video-toggle"><summary>Show preview</summary><video controls preload="none" aria-label={`Video to review from @${job.sourcePost.sourceAccount.username}`} src={`/media/${job.sourcePost.platformPostId}`} /></details></div> : <div className="asset-thumb placeholder">No media</div>}</div><div className="review-main"><label className="review-select"><input form="bulk-review" type="checkbox" name="publishJobId" value={job.id} /> Select for bulk action</label><strong>@{job.sourcePost.sourceAccount.username} · X status {job.sourcePost.platformPostId}</strong><small>{job.sourcePost.sourceUrl}</small><Badge value={job.status} />{job.scheduledFor ? <small className="review-schedule">Scheduled for {new Date(job.scheduledFor).toLocaleString()}</small> : null}
          <p className="form-note">Collected from {job.sourcePost.discoveryKind === "BOOKMARK" ? "collector bookmarks" : "source profile"}. Source caption: {job.sourcePost.text || "No source caption"}</p>
          {job.sourcePost.duplicateGroup && <div className="error-line">Duplicate group: {job.sourcePost.duplicateReason ?? job.sourcePost.duplicateGroup.detectionKind}<ActionForm action={restoreDuplicate}><input type="hidden" name="sourcePostId" value={job.sourcePost.id} /><SubmitButton>Restore for review</SubmitButton></ActionForm></div>}
          <ActionForm action={approveReview} className="stack-form"><input type="hidden" name="publishJobId" value={job.id} /><label>Caption<textarea name="caption" defaultValue={job.caption} maxLength={280} required /></label><label>Internal notes<textarea name="reviewNotes" defaultValue={job.sourcePost.reviewNotes ?? ""} maxLength={2000} /></label><label>Tags<input name="internalTags" defaultValue={job.sourcePost.internalTags ?? ""} maxLength={500} /></label><label>Schedule time (local, optional)<input name="scheduledFor" type="datetime-local" step="60" /><small className="form-note">Leave empty to approve and queue this post only for the publisher worker now.</small></label><SubmitButton className="small-button accent-button" pending="Approving…">Approve this post only</SubmitButton></ActionForm>
          <ActionForm action={resolveReviewCaption}><input type="hidden" name="publishJobId" value={job.id} /><SubmitButton>Apply caption rules</SubmitButton></ActionForm>
          <ActionForm action={rejectReview}><input type="hidden" name="publishJobId" value={job.id} /><ConfirmSubmitButton message="Reject this content?">Reject</ConfirmSubmitButton></ActionForm>
          <ActionForm action={returnToDownloads}><input type="hidden" name="publishJobId" value={job.id} /><ConfirmSubmitButton message="Return this review item to Downloads?">Return to Downloads</ConfirmSubmitButton></ActionForm>
        </div>
      </article>)}</div>}
    </section>
    {duplicates.length > 0 && <section className="panel"><div className="panel-head"><div><p className="eyebrow">Skipped duplicates</p><h3>{duplicates.length} item{duplicates.length === 1 ? "" : "s"}</h3></div></div><div className="source-list">{duplicates.map((post) => <article className="source-row" key={post.id}><div className="source-main"><strong>@{post.sourceAccount.username} · X status {post.platformPostId}</strong><small>{post.duplicateReason}</small>{post.mediaAsset && <video controls preload="metadata" src={`/media/${post.platformPostId}`} style={{ maxWidth: "360px", display: "block", marginTop: "12px" }} />}<ActionForm action={restoreDuplicate}><input type="hidden" name="sourcePostId" value={post.id} /><SubmitButton>Restore for review</SubmitButton></ActionForm></div></article>)}</div></section>}
  </Shell>;
}
