import { checkIdentitySession, clearAllBrowserProfiles, createBrowserIdentity, deleteIdentityPermanently, deleteIdentityProfile, openIdentityLogin, resetAllData, saveCaptionSettings, saveDiscordNotificationSettings, saveNotificationSettings, saveReviewSettings, saveSettings, sendDiscordTestNotification, sendTestNotification, toggleBrowserIdentity, toggleIdentityAutomatic, updateIdentityBrowser, verifyNotificationConnection } from "../actions";
import { ActionForm, ConfirmSubmitButton, SubmitButton } from "../controls";
import { getResetPreview, getSettings } from "../lib/data";
import { Badge, Empty, Shell } from "../ui";

export const dynamic = "force-dynamic";

type SearchParams = { captionSaved?: string; identityCreated?: string; profileOpened?: string; profileDeleted?: string; allProfilesDeleted?: string; reviewSaved?: string; notificationsSaved?: string; discordNotificationsSaved?: string; notificationTest?: string; notificationTestError?: string; discordNotificationTest?: string; discordNotificationTestError?: string; notificationVerify?: string; notificationVerifyError?: string; botUsername?: string; botName?: string; chatTitle?: string; chatError?: string; identityDeleted?: string };

export default async function SettingsPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  const params = await searchParams;
  const [settings, reset] = await Promise.all([getSettings(), getResetPreview()]);
  const collectors = settings.identities.filter((identity) => identity.role === "COLLECTOR" && identity.profilePresent);
  const publishers = settings.identities.filter((identity) => identity.role === "PUBLISHER" && identity.profilePresent);
  const browserOptions = settings.installedBrowsers;

  const identityLane = (role: "COLLECTOR" | "PUBLISHER", identities: typeof settings.identities) => {
    const collector = role === "COLLECTOR";
    return <section className={`identity-lane ${collector ? "collector-lane" : "publisher-lane"}`}>
      <header className="identity-lane-head"><div><p className="eyebrow">{collector ? "Inbound / Collector" : "Outbound / Publisher"}</p><h3>{collector ? "Collector identities" : "Publisher identities"}</h3><p>{collector ? "Read assigned source profiles and private bookmarks from X." : "Publish independently targeted review jobs to X."}</p></div><span className="identity-role-mark" aria-hidden="true">{collector ? "↓" : "↑"}</span></header>
      <div className="identity-card-list">
        {identities.length === 0 && <Empty>No {collector ? "Collector" : "Publisher"} browser profile exists.</Empty>}
        {identities.map((identity) => <article className="identity-card" key={identity.id}>
          <div className="identity-card-title"><div><small>{identity.label}</small><strong>{identity.expectedUsername ? `@${identity.expectedUsername}` : "X identity not set"}</strong></div><div className="identity-badges"><Badge value={identity.verified ? "VERIFIED" : "NEEDS_VERIFY"} />{identity.busy && <Badge value="RUNNING" />}</div></div>
          <dl className="identity-facts"><div><dt>Browser</dt><dd>{identity.browserId}</dd></div><div><dt>Profile files</dt><dd>{identity.profilePresent ? "Present" : identity.profileDeletedAt ? `Deleted ${new Date(identity.profileDeletedAt).toLocaleString()}` : "Not created"}</dd></div><div><dt>Session</dt><dd>{identity.verified ? `Verified ${new Date(identity.verifiedAt!).toLocaleString()}` : "Not verified"}</dd></div><div><dt>{collector ? "Assigned sources" : "Publication targets"}</dt><dd>{collector ? identity._count.assignedSources : identity._count.publishJobs}</dd></div></dl>
          {identity.verificationError && <p className="toast error" role="alert">{identity.verificationError}</p>}
          {!collector && settings.publishMode === "AUTOMATIC" && !identity.automaticEnabled && <p className="toast warning" role="status">Automatic publishing is off for this Publisher. Scheduled posts will not auto-run until you enable it below.</p>}
          {params.profileOpened === identity.id && <p className="toast bookmark-success" role="status">Profile opened. Sign in as @{identity.expectedUsername}, close the browser completely, then verify this identity.</p>}
          <details className="identity-technical"><summary>Browser and technical details</summary><small>Executable</small><code>{identity.executablePath ?? "Browser channel"}</code><small>Managed profile</small><code>{identity.profilePath}</code><ActionForm action={updateIdentityBrowser} className="form-panel"><input type="hidden" name="identityId" value={identity.id} /><label>Change browser<select name="browserId" defaultValue={identity.browserId}>{browserOptions.map((browser) => <option key={`${identity.id}-${browser.id}-${browser.executablePath}`} value={browser.id}>{browser.name}</option>)}<option value="custom">Custom Chromium executable</option></select></label><label>Custom executable path<input name="customExecutablePath" defaultValue={identity.browserId === "custom" ? identity.executablePath ?? "" : ""} /></label><SubmitButton>Save browser</SubmitButton></ActionForm></details>
          <div className="identity-actions">
            <ActionForm action={openIdentityLogin}><input type="hidden" name="identityId" value={identity.id} /><SubmitButton pending="Opening…">Open X profile</SubmitButton></ActionForm>
            <ActionForm action={checkIdentitySession}><input type="hidden" name="identityId" value={identity.id} /><SubmitButton className="small-button accent-button" pending="Verifying…">Verify identity</SubmitButton></ActionForm>
            <ActionForm action={toggleBrowserIdentity}><input type="hidden" name="identityId" value={identity.id} /><input type="hidden" name="enabled" value={String(!identity.enabled)} /><SubmitButton>{identity.enabled ? "Pause identity" : "Enable identity"}</SubmitButton></ActionForm>
            {!collector && <ActionForm action={toggleIdentityAutomatic}><input type="hidden" name="identityId" value={identity.id} /><input type="hidden" name="automatic" value={String(!identity.automaticEnabled)} /><SubmitButton>{identity.automaticEnabled ? "Disable automatic" : "Enable automatic"}</SubmitButton></ActionForm>}
            {identity.managed ? <ActionForm action={deleteIdentityProfile}><input type="hidden" name="identityId" value={identity.id} /><ConfirmSubmitButton message={`Delete the local ${collector ? "Collector" : "Publisher"} profile for @${identity.expectedUsername}? Cookies and login data will be removed, while the identity and its work remain.`}>Delete local profile</ConfirmSubmitButton></ActionForm> : <span className="form-note">Legacy profile preserved outside managed identity storage.</span>}
            <ActionForm action={deleteIdentityPermanently} className="inline-form"><input type="hidden" name="identityId" value={identity.id} /><input name="confirmation" placeholder={`DELETE ${identity.label}`} aria-label={`Type DELETE ${identity.label} to confirm permanent deletion`} required /><ConfirmSubmitButton message={`Permanently delete ${identity.label} and all of its browser profile files? Existing publish jobs will be detached and marked Legacy Publisher, and assigned sources will be unassigned. This cannot be undone.`}>Delete permanently</ConfirmSubmitButton></ActionForm>
          </div>
        </article>)}
      </div>
      <details className="identity-add"><summary>Add browser profile</summary><ActionForm action={createBrowserIdentity} className="form-panel"><input type="hidden" name="role" value={role} /><label>Browser<select name="browserId" required>{browserOptions.map((browser) => <option key={`${role}-${browser.id}-${browser.executablePath}`} value={browser.id}>{browser.name}</option>)}<option value="custom">Custom Chromium executable</option></select></label><label>Custom executable path<input name="customExecutablePath" placeholder="Only required for Custom" /></label><SubmitButton className="button primary" pending="Opening…">Add browser profile</SubmitButton></ActionForm></details>
    </section>;
  };

  return <Shell title="Settings" eyebrow="Cenblue / local configuration">
    {params.identityCreated && <div className="toast bookmark-success" role="status">Browser identity created. Open its profile to sign into X.</div>}
    {params.profileDeleted && <div className="toast bookmark-success" role="status">Browser profile deleted. Its local cookies and X session were removed.</div>}
    {params.identityDeleted && <div className="toast bookmark-success" role="status">Browser identity permanently deleted. Its profile files were removed and its work was detached.</div>}
    {params.allProfilesDeleted !== undefined && <div className="toast bookmark-success" role="status">All managed browser profiles were deleted. {Number(params.allProfilesDeleted)} identities were preserved and now require login and verification.</div>}

    <section className="panel identity-workspace"><div className="panel-head"><div><p className="eyebrow">Isolated X identities</p><h2>Know exactly who reads and who publishes.</h2></div><Badge value={settings.identities.some((identity) => identity.busy) ? "RUNNING" : "AVAILABLE"} /></div><p className="form-note browser-intro">Every identity owns a separate local browser profile. Collector and Publisher colors, direction marks, account checks, jobs, and leases stay distinct.</p><div className="identity-lanes">{identityLane("COLLECTOR", collectors)}{identityLane("PUBLISHER", publishers)}</div></section>

    <ActionForm action={saveSettings} className="settings-grid">
      <section className="panel form-panel"><p className="eyebrow">Collection</p><h3>Source cadence</h3><label>Collection interval <span className="input-suffix">minutes</span><input name="collectionIntervalMinutes" type="number" min="1" max="59" defaultValue={settings.collectionIntervalMinutes} required /></label><label>Maximum posts per source<input name="postsPerSource" type="number" min="1" max="100" defaultValue={settings.postsPerSource} required /></label><label>Enabled source account limit<input name="sourceAccountLimit" type="number" min="1" max="100" defaultValue={settings.sourceAccountLimit} required /></label></section>
      <section className="panel form-panel"><p className="eyebrow">Publishing</p><h3>Output behavior</h3><label>Publish interval <span className="input-suffix">minutes</span><input name="publishIntervalMinutes" type="number" min="1" defaultValue={settings.publishIntervalMinutes} required /></label><label>Publish mode<select name="publishMode" defaultValue={settings.publishMode}><option value="ASSISTED">Assisted</option><option value="AUTOMATIC">Automatic</option></select></label><label>Minimum expected upload speed <span className="input-suffix">Mbps</span><input name="publishMinUploadMbps" type="number" min="0.25" max="1000" step="0.25" defaultValue={settings.publishMinUploadMbps} required /></label><label>Maximum upload wait <span className="input-suffix">minutes</span><input name="publishMaxUploadMinutes" type="number" min="5" max="120" defaultValue={settings.publishMaxUploadMinutes} required /></label><label>Download worker concurrency<input name="downloadConcurrency" type="number" min="1" max="3" defaultValue={settings.downloadConcurrency} required /></label><label>Downloads per run<input name="downloadBatchLimit" type="number" min="1" max="1000" defaultValue={settings.downloadBatchLimit} required /></label><label>Daily minimum posts<input name="dailyMinimum" type="number" min="0" max="20" defaultValue={settings.dailyMinimum} required /></label><label>Daily preferred posts<input name="dailyPreferred" type="number" min="0" max="20" defaultValue={settings.dailyPreferred} required /></label></section>
      <section className="panel form-panel"><p className="eyebrow">Runtime</p><h3>Browser behavior</h3><label>Application timezone<input name="timezone" defaultValue={settings.timezone} placeholder="Asia/Jakarta" required /></label><label>Headless mode<select name="headless" defaultValue={settings.headless}><option value="false">Visible browser</option><option value="true">Headless</option></select></label><SubmitButton className="button primary" pending="Saving…">Save runtime settings</SubmitButton></section>
    </ActionForm>

    <ActionForm action={saveCaptionSettings} className="panel form-panel caption-settings"><p className="eyebrow">Captioning</p><h3>Rotation templates</h3><label>Templates<textarea name="captionTemplates" defaultValue={settings.captionTemplates} rows={10} /></label><p className="form-note">Separate rotating templates with a line containing only <code>---</code>.</p><SubmitButton className="button primary" pending="Saving captions…">Save caption settings</SubmitButton>{params.captionSaved === "1" && <div className="toast bookmark-success" role="status">Caption settings saved and Review captions refreshed.</div>}</ActionForm>

    <ActionForm action={saveReviewSettings} className="panel form-panel review-settings"><p className="eyebrow">Review</p><h3>Preview behavior</h3><label>Video preview in review modal<select name="videoPreviewEnabled" defaultValue={settings.reviewVideoPreviewEnabled}><option value="false">Hidden by default</option><option value="true">Visible by default</option></select></label><p className="form-note">The preview can still be toggled on inside each review item. This only sets the default when opening the review modal.</p><SubmitButton className="button primary" pending="Saving…">Save review settings</SubmitButton>{params.reviewSaved === "1" && <div className="toast bookmark-success" role="status">Review settings saved.</div>}</ActionForm>

    <ActionForm action={saveNotificationSettings} className="panel form-panel"><p className="eyebrow">Notifications</p><h3>Telegram alerts</h3><label>Notifications<select name="notificationsEnabled" defaultValue={settings.notificationsEnabled}><option value="false">Disabled</option><option value="true">Enabled</option></select></label><label>Telegram chat ID<input name="telegramChatId" defaultValue={settings.telegramChatId} placeholder="123456789" /></label>{!settings.telegramTokenConfigured && <p className="form-note">Set <code>TELEGRAM_BOT_TOKEN</code> in <code>.env</code> and restart the dashboard to enable alerts.</p>}<p className="form-note">Alerts notify on publish failures that require attention. Publish-mode, caption, and identity details stay out of the message. Find your chat ID by messaging your bot, then checking <code>@userinfobot</code>.</p><SubmitButton className="button primary" pending="Saving…">Save notification settings</SubmitButton>{params.notificationsSaved === "1" && <div className="toast bookmark-success" role="status">Notification settings saved.</div>}{params.notificationTest === "delivered" && <div className="toast bookmark-success" role="status">Test message delivered to Telegram.</div>}{params.notificationTest === "error" && <div className="toast error" role="alert">Test message failed: {params.notificationTestError}</div>}{params.notificationVerify === "ok" && <div className="toast bookmark-success" role="status">Bot connected: @{params.botUsername} ({params.botName}).</div>}{params.notificationVerify === "all" && <div className="toast bookmark-success" role="status">Bot connected: @{params.botUsername} · chat reachable ({params.chatTitle ?? "private chat"}).</div>}{params.notificationVerify === "noChat" && <div className="toast" role="status">Bot connected: @{params.botUsername}. Set a chat ID and verify again.</div>}{params.notificationVerify === "chatError" && <div className="toast error" role="alert">Bot OK, but chat check failed: {decodeURIComponent(params.chatError ?? "")}. The bot must be started in that chat first.</div>}{params.notificationVerify === "tokenError" && <div className="toast error" role="alert">Bot check failed: {decodeURIComponent(params.notificationVerifyError ?? "")}</div>}
      <div className="notification-status"><span className="eyebrow">Status</span><dl>{[["Bot token", settings.notificationStatus.tokenConfigured ? (settings.notificationStatus.tokenValid ? `valid · @${settings.notificationStatus.botUsername}` : "set but invalid") : "not configured"], ["Chat ID", settings.notificationStatus.chatReachable ? `reachable${settings.notificationStatus.chatTitle ? ` · ${settings.notificationStatus.chatTitle}` : ""}` : settings.notificationStatus.chatSet ? "not reachable" : "not set"], ["Pending", `${settings.notificationStatus.outbox.pending} queued · ${settings.notificationStatus.outbox.sending} sending`], ["Delivered", `${settings.notificationStatus.outbox.sent} total${settings.notificationStatus.lastDeliveredAt ? ` · last ${new Date(settings.notificationStatus.lastDeliveredAt).toLocaleString()}` : ""}`], ["Failed", settings.notificationStatus.lastError ? settings.notificationStatus.lastError : `${settings.notificationStatus.outbox.dead} dead · none`]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd className="[overflow-wrap:anywhere]">{value}</dd></div>)}</dl></div></ActionForm><div className="notification-actions"><ActionForm action={verifyNotificationConnection} className="inline-form"><SubmitButton className="small-button" pending="Verifying…">Verify connection</SubmitButton></ActionForm><ActionForm action={sendTestNotification} className="inline-form"><SubmitButton className="small-button accent-button" pending="Sending…">Send test message</SubmitButton></ActionForm></div>

    <ActionForm action={saveDiscordNotificationSettings} className="panel form-panel"><p className="eyebrow">Discord</p><h3>Direct-message alerts</h3><label>Notifications<select name="discordNotificationsEnabled" defaultValue={settings.discordNotificationsEnabled}><option value="false">Disabled</option><option value="true">Enabled</option></select></label>{!settings.discordBotTokenConfigured && <p className="form-note">Set <code>DISCORD_BOT_TOKEN</code> in <code>.env</code> and restart the dashboard to enable alerts.</p>}{!settings.discordOwnerConfigured && <p className="form-note">Set <code>DISCORD_OWNER_ID</code> in <code>.env</code> so the bot knows who to DM.</p>}<p className="form-note">Publish-failure alerts are sent to your direct message with the bot. The bot must be running and DMed once so Discord opens the DM channel.</p><SubmitButton className="button primary" pending="Saving…">Save Discord settings</SubmitButton>{params.discordNotificationsSaved === "1" && <div className="toast bookmark-success" role="status">Discord settings saved.</div>}{params.discordNotificationTest === "delivered" && <div className="toast bookmark-success" role="status">Test message delivered to your Discord DM.</div>}{params.discordNotificationTest === "error" && <div className="toast error" role="alert">Test message failed: {params.discordNotificationTestError}</div>}<div className="notification-status"><span className="eyebrow">Status</span><dl>{[["Bot", settings.discordBotConnected ? "connected" : "not connected"], ["Owner", settings.discordOwnerId ? settings.discordOwnerId : "not configured"]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd className="[overflow-wrap:anywhere]">{value}</dd></div>)}</dl></div></ActionForm><div className="notification-actions"><ActionForm action={sendDiscordTestNotification} className="inline-form"><SubmitButton className="small-button accent-button" pending="Sending…">Send test DM</SubmitButton></ActionForm></div>

    <section className="panel form-panel profile-danger"><p className="eyebrow">Browser credential cleanup</p><h3>Clear all managed browser profiles</h3><div className="reset-preview"><span>{collectors.length} Collector identities</span><span>{publishers.length} Publisher identities</span><span>{settings.identities.filter((identity) => identity.profilePresent).length} profiles currently present</span></div><p className="form-note">Deletes every Collector and Publisher profile under managed storage, including inactive profiles. Identity labels, browser preferences, source assignments, jobs, media, and history remain.</p><ActionForm action={clearAllBrowserProfiles} className="inline-form"><label className="sr-only" htmlFor="profile-reset-confirmation">Confirmation</label><input id="profile-reset-confirmation" name="confirmation" placeholder="DELETE ALL PROFILES" required /><ConfirmSubmitButton message="Delete every managed Collector and Publisher browser profile and local X session?">Clear all browser profiles</ConfirmSubmitButton></ActionForm></section>

    <section className="panel form-panel"><p className="eyebrow">Application data</p><h3>Reset all application data</h3><div className="reset-preview"><span>{reset.sources} sources</span><span>{reset.posts} posts</span><span>{reset.downloads + reset.publishes} jobs</span><span>{reset.media} media records</span></div><p className="form-note">Browser profiles are preserved unless you use the separate browser credential cleanup above.</p>{reset.active > 0 ? <p className="error-line">Reset is unavailable while {reset.active} operations are running.</p> : <ActionForm action={resetAllData} className="inline-form"><input name="confirmation" placeholder="Type RESET ALL" required /><ConfirmSubmitButton message="Reset all Cenblue data except videos and browser profiles?">Reset all data</ConfirmSubmitButton></ActionForm>}</section>
  </Shell>;
}
