import { resetAllData, saveCaptionSettings, saveSettings } from "../actions";
import { ActionForm, ConfirmSubmitButton, SubmitButton } from "../controls";
import { getResetPreview, getSettings } from "../lib/data";
import { Badge, Shell } from "../ui";

export const dynamic = "force-dynamic";

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ captionSaved?: string }> }) {
  const params = await searchParams;
  const [settings, reset] = await Promise.all([getSettings(), getResetPreview()]);
  return <Shell title="Settings" eyebrow="Cenbluee / local configuration">
    <ActionForm action={saveSettings} className="settings-grid">
      <section className="panel form-panel"><p className="eyebrow">Collection</p><h3>Source cadence</h3><label>Collection interval <span className="input-suffix">minutes</span><input name="collectionIntervalMinutes" type="number" min="1" max="59" defaultValue={settings.collectionIntervalMinutes} required /></label><label>Maximum posts per source<input name="postsPerSource" type="number" min="1" max="100" defaultValue={settings.postsPerSource} required /></label><label>Enabled source account limit<input name="sourceAccountLimit" type="number" min="1" max="100" defaultValue={settings.sourceAccountLimit} required /></label><p className="form-note">Collection searches until the eligible target, timeline exhaustion, or the configured safety budget.</p></section>
      <section className="panel form-panel"><p className="eyebrow">Publishing</p><h3>Output behavior</h3><label>Publish interval <span className="input-suffix">minutes</span><input name="publishIntervalMinutes" type="number" min="1" defaultValue={settings.publishIntervalMinutes} required /></label><label>Publish mode<select name="publishMode" defaultValue={settings.publishMode}><option value="ASSISTED">Assisted</option><option value="AUTOMATIC">Automatic</option></select></label><label>Minimum expected upload speed <span className="input-suffix">Mbps</span><input name="publishMinUploadMbps" type="number" min="0.25" max="1000" step="0.25" defaultValue={settings.publishMinUploadMbps} required /></label><label>Maximum upload wait <span className="input-suffix">minutes</span><input name="publishMaxUploadMinutes" type="number" min="5" max="120" defaultValue={settings.publishMaxUploadMinutes} required /></label><p className="form-note">Cenblue combines media size, duration, and this conservative speed estimate to calculate each upload deadline.</p><label>Download worker concurrency<input name="downloadConcurrency" type="number" min="1" max="3" defaultValue={settings.downloadConcurrency} required /></label><label>Downloads per run<input name="downloadBatchLimit" type="number" min="1" max="1000" defaultValue={settings.downloadBatchLimit} required /></label><p className="form-note">Each manual or scheduled download cycle stops after attempting this many queued posts.</p><label>Daily minimum posts<input name="dailyMinimum" type="number" min="0" max="20" defaultValue={settings.dailyMinimum} required /></label><label>Daily preferred posts<input name="dailyPreferred" type="number" min="0" max="20" defaultValue={settings.dailyPreferred} required /></label></section>
      <section className="panel form-panel"><p className="eyebrow">Runtime</p><h3>Browser behavior</h3><label>Application timezone<input name="timezone" defaultValue={settings.timezone} placeholder="Asia/Jakarta" required /></label><p className="form-note">Schedules and operational dates use this IANA timezone on every device.</p><label>Headless mode<select name="headless" defaultValue={settings.headless}><option value="false">Visible browser</option><option value="true">Headless</option></select></label><SubmitButton className="button primary" pending="Saving…">Save collection, publishing & runtime <span>↓</span></SubmitButton></section>
    </ActionForm>
    <ActionForm action={saveCaptionSettings} className="panel form-panel caption-settings"><p className="eyebrow">Captioning</p><h3>Rotation templates</h3><label>Templates<textarea name="captionTemplates" defaultValue={settings.captionTemplates} rows={10} /></label><p className="form-note">Write one template normally. To rotate several templates, place <code>---</code> alone on a line between them. Two hyphens (<code>--</code>) are ordinary caption text.</p><pre className="caption-example">{`{sourceCaption}\n\nShared via Cenblue\n---\n{sourceCaption}\n\nSource: {sourceUsername}`}</pre><p className="form-note">Available placeholders: <code>{`{sourceCaption}`}</code>, <code>{`{sourceUsername}`}</code>, <code>{`{sourceUrl}`}</code>, and <code>{`{postId}`}</code>. Per-source caption rules override this global rotation. Saving also refreshes captions currently waiting in Review.</p><SubmitButton className="button primary" pending="Saving captions…">Save caption settings <span>↓</span></SubmitButton>{params.captionSaved === "1" && <div className="toast bookmark-success" role="status">Caption settings saved and current Review captions refreshed.</div>}</ActionForm>
    <section className="panel"><div className="panel-head"><div><p className="eyebrow">Effective runtime</p><h3>Isolated browser identities</h3></div><Badge value={settings.collectorBrowserBusy || settings.publisherBrowserBusy ? "RUNNING" : "AVAILABLE"} /></div><div className="runtime-grid"><div><small>Repository root</small><strong>{settings.repositoryRoot}</strong></div><div><small>Browser</small><strong>{settings.browserChannel}</strong></div><div><small>Collector user-data root</small><strong>{settings.collectorProfilePath}</strong></div><div><small>Collector internal profile</small><strong>{settings.collectorProfileDirectory}</strong></div><div><small>Collector session</small><strong>{settings.collectorSessionVerifiedAt ? new Date(settings.collectorSessionVerifiedAt).toLocaleString() : "Not checked"}</strong></div><div><small>Collector state</small><strong>{settings.collectorBrowserBusy ? "Browser busy" : "Available"}</strong></div><div><small>Publisher user-data root</small><strong>{settings.publisherProfilePath}</strong></div><div><small>Publisher internal profile</small><strong>{settings.publisherProfileDirectory}</strong></div><div><small>Publisher session</small><strong>{settings.publisherSessionVerifiedAt ? new Date(settings.publisherSessionVerifiedAt).toLocaleString() : "Not checked"}</strong></div><div><small>Publisher state</small><strong>{settings.publisherBrowserBusy ? "Browser busy" : "Available"}</strong></div></div><p className="form-note">Collector and publisher profiles must stay separate. Restart the dashboard after changing either profile path in `.env`.</p></section>
    <section className="panel"><p className="eyebrow">Device setup</p><h3>Move preferences without moving credentials</h3><p className="form-note">Run <code>pnpm setup</code> on a new device to detect media tools, create storage, migrate the database, and configure isolated browser profiles. Transfer settings and managed source rules with <code>pnpm config:export</code> and <code>pnpm config:import &lt;file&gt;</code>. Browser cookies, media, history, and machine paths are intentionally excluded.</p></section>
    <section className="panel form-panel"><p className="eyebrow">Danger zone</p><h3>Reset all application data</h3><div className="reset-preview"><span>{reset.sources} sources</span><span>{reset.posts} posts</span><span>{reset.downloads + reset.publishes} jobs</span><span>{reset.media} media records</span></div><p className="form-note">Creates a recovery database snapshot in `storage/reset-recovery`, then deletes the listed database records, settings, logs, thumbnails, temporary files, and normal backups. Videos in `storage/videos` are intentionally preserved and will become unmanaged orphan files.</p>{reset.active > 0 ? <p className="error-line">Reset is unavailable while {reset.active} operation{reset.active === 1 ? " is" : "s are"} running.</p> : <ActionForm action={resetAllData} className="inline-form"><label className="sr-only" htmlFor="reset-confirmation">Confirmation</label><input id="reset-confirmation" name="confirmation" placeholder="Type RESET ALL" required /><ConfirmSubmitButton message="Reset all Cenblue data except videos? This cannot be undone.">Reset all data</ConfirmSubmitButton></ActionForm>}</section>
  </Shell>;
}
